// Generated by CoffeeScript 1.4.0
(function() {
  var Criteria;

  Criteria = (function() {

    function Criteria() {}

    Criteria.prototype.fieldName = "";

    return Criteria;

  })();

  window.Criteria = Criteria;

}).call(this);
