// Generated by CoffeeScript 1.4.0
(function() {

  describe("CallListSettings", function() {
    var callListSettings;
    callListSettings = void 0;
    return beforeEach(function() {
      return callListSettings = new CallListSettings();
    });
  });

}).call(this);
