// Generated by CoffeeScript 1.4.0
(function() {

  describe("Criteria", function() {
    var criteria;
    criteria = void 0;
    beforeEach(function() {
      return criteria = new Criteria();
    });
    it("Criteria should have a variable", function() {
      criteria.fieldName = "fieldname";
      return expect(criteria.fieldName).toEqual('fieldname');
    });
    return it("Criteria should have an operator", function() {
      criteria.operator = "=";
      return expect(criteria.operator).toEqual("=");
    });
  });

}).call(this);
