// Generated by CoffeeScript 1.4.0
(function() {

  describe("Query", function() {
    var query;
    query = void 0;
    return beforeEach(function() {
      return query = new Query();
    });
  });

}).call(this);
