// Generated by CoffeeScript 1.4.0
(function() {

  describe("Scenario", function() {
    var scenario;
    scenario = void 0;
    return beforeEach(function() {
      return scenario = new Scenario();
    });
  });

}).call(this);
